# Generated by Django 5.0.7 on 2026-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
