# Generated by Django 5.0.7 on 2026-02-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
